# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-11 10:12
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('puput', '0002_auto_20150919_0925'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='blogpage',
            managers=[
                ('extra', django.db.models.manager.Manager()),
            ],
        ),
    ]
